# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/preeti/mysql-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/preeti/mysql-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Client\" \"DebugBinaries\" \"Development\" \"Documentation\" \"Embedded\" \"Info\" \"IniFiles\" \"ManPages\" \"Readme\" \"Server\" \"Server_Scripts\" \"SharedLibraries\" \"SupportFiles\" \"Test\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/preeti/mysql-server/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/preeti/mysql-server/CMakeFiles /home/preeti/mysql-server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/preeti/mysql-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named INFO_BIN

# Build rule for target.
INFO_BIN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 INFO_BIN
.PHONY : INFO_BIN

# fast build rule for target.
INFO_BIN/fast:
	$(MAKE) -f CMakeFiles/INFO_BIN.dir/build.make CMakeFiles/INFO_BIN.dir/build
.PHONY : INFO_BIN/fast

#=============================================================================
# Target rules for targets named INFO_SRC

# Build rule for target.
INFO_SRC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 INFO_SRC
.PHONY : INFO_SRC

# fast build rule for target.
INFO_SRC/fast:
	$(MAKE) -f CMakeFiles/INFO_SRC.dir/build.make CMakeFiles/INFO_SRC.dir/build
.PHONY : INFO_SRC/fast

#=============================================================================
# Target rules for targets named abi_check

# Build rule for target.
abi_check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 abi_check
.PHONY : abi_check

# fast build rule for target.
abi_check/fast:
	$(MAKE) -f CMakeFiles/abi_check.dir/build.make CMakeFiles/abi_check.dir/build
.PHONY : abi_check/fast

#=============================================================================
# Target rules for targets named abi_check_all

# Build rule for target.
abi_check_all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 abi_check_all
.PHONY : abi_check_all

# fast build rule for target.
abi_check_all/fast:
	$(MAKE) -f CMakeFiles/abi_check_all.dir/build.make CMakeFiles/abi_check_all.dir/build
.PHONY : abi_check_all/fast

#=============================================================================
# Target rules for targets named ctags

# Build rule for target.
ctags: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ctags
.PHONY : ctags

# fast build rule for target.
ctags/fast:
	$(MAKE) -f CMakeFiles/ctags.dir/build.make CMakeFiles/ctags.dir/build
.PHONY : ctags/fast

#=============================================================================
# Target rules for targets named tags

# Build rule for target.
tags: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tags
.PHONY : tags

# fast build rule for target.
tags/fast:
	$(MAKE) -f CMakeFiles/tags.dir/build.make CMakeFiles/tags.dir/build
.PHONY : tags/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f zlib/CMakeFiles/zlib.dir/build.make zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named yassl

# Build rule for target.
yassl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yassl
.PHONY : yassl

# fast build rule for target.
yassl/fast:
	$(MAKE) -f extra/yassl/CMakeFiles/yassl.dir/build.make extra/yassl/CMakeFiles/yassl.dir/build
.PHONY : yassl/fast

#=============================================================================
# Target rules for targets named taocrypt

# Build rule for target.
taocrypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taocrypt
.PHONY : taocrypt

# fast build rule for target.
taocrypt/fast:
	$(MAKE) -f extra/yassl/taocrypt/CMakeFiles/taocrypt.dir/build.make extra/yassl/taocrypt/CMakeFiles/taocrypt.dir/build
.PHONY : taocrypt/fast

#=============================================================================
# Target rules for targets named edit

# Build rule for target.
edit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edit
.PHONY : edit

# fast build rule for target.
edit/fast:
	$(MAKE) -f cmd-line-utils/libedit/CMakeFiles/edit.dir/build.make cmd-line-utils/libedit/CMakeFiles/edit.dir/build
.PHONY : edit/fast

#=============================================================================
# Target rules for targets named event

# Build rule for target.
event: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 event
.PHONY : event

# fast build rule for target.
event/fast:
	$(MAKE) -f libevent/CMakeFiles/event.dir/build.make libevent/CMakeFiles/event.dir/build
.PHONY : event/fast

#=============================================================================
# Target rules for targets named event_share

# Build rule for target.
event_share: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 event_share
.PHONY : event_share

# fast build rule for target.
event_share/fast:
	$(MAKE) -f libevent/CMakeFiles/event_share.dir/build.make libevent/CMakeFiles/event_share.dir/build
.PHONY : event_share/fast

#=============================================================================
# Target rules for targets named perfschema

# Build rule for target.
perfschema: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perfschema
.PHONY : perfschema

# fast build rule for target.
perfschema/fast:
	$(MAKE) -f storage/perfschema/CMakeFiles/perfschema.dir/build.make storage/perfschema/CMakeFiles/perfschema.dir/build
.PHONY : perfschema/fast

#=============================================================================
# Target rules for targets named pfs-t

# Build rule for target.
pfs-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs-t
.PHONY : pfs-t

# fast build rule for target.
pfs-t/fast:
	$(MAKE) -f storage/perfschema/unittest/CMakeFiles/pfs-t.dir/build.make storage/perfschema/unittest/CMakeFiles/pfs-t.dir/build
.PHONY : pfs-t/fast

#=============================================================================
# Target rules for targets named pfs_account-oom-t

# Build rule for target.
pfs_account-oom-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs_account-oom-t
.PHONY : pfs_account-oom-t

# fast build rule for target.
pfs_account-oom-t/fast:
	$(MAKE) -f storage/perfschema/unittest/CMakeFiles/pfs_account-oom-t.dir/build.make storage/perfschema/unittest/CMakeFiles/pfs_account-oom-t.dir/build
.PHONY : pfs_account-oom-t/fast

#=============================================================================
# Target rules for targets named pfs_connect_attr-t

# Build rule for target.
pfs_connect_attr-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs_connect_attr-t
.PHONY : pfs_connect_attr-t

# fast build rule for target.
pfs_connect_attr-t/fast:
	$(MAKE) -f storage/perfschema/unittest/CMakeFiles/pfs_connect_attr-t.dir/build.make storage/perfschema/unittest/CMakeFiles/pfs_connect_attr-t.dir/build
.PHONY : pfs_connect_attr-t/fast

#=============================================================================
# Target rules for targets named pfs_host-oom-t

# Build rule for target.
pfs_host-oom-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs_host-oom-t
.PHONY : pfs_host-oom-t

# fast build rule for target.
pfs_host-oom-t/fast:
	$(MAKE) -f storage/perfschema/unittest/CMakeFiles/pfs_host-oom-t.dir/build.make storage/perfschema/unittest/CMakeFiles/pfs_host-oom-t.dir/build
.PHONY : pfs_host-oom-t/fast

#=============================================================================
# Target rules for targets named pfs_instr-oom-t

# Build rule for target.
pfs_instr-oom-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs_instr-oom-t
.PHONY : pfs_instr-oom-t

# fast build rule for target.
pfs_instr-oom-t/fast:
	$(MAKE) -f storage/perfschema/unittest/CMakeFiles/pfs_instr-oom-t.dir/build.make storage/perfschema/unittest/CMakeFiles/pfs_instr-oom-t.dir/build
.PHONY : pfs_instr-oom-t/fast

#=============================================================================
# Target rules for targets named pfs_instr-t

# Build rule for target.
pfs_instr-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs_instr-t
.PHONY : pfs_instr-t

# fast build rule for target.
pfs_instr-t/fast:
	$(MAKE) -f storage/perfschema/unittest/CMakeFiles/pfs_instr-t.dir/build.make storage/perfschema/unittest/CMakeFiles/pfs_instr-t.dir/build
.PHONY : pfs_instr-t/fast

#=============================================================================
# Target rules for targets named pfs_instr_class-oom-t

# Build rule for target.
pfs_instr_class-oom-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs_instr_class-oom-t
.PHONY : pfs_instr_class-oom-t

# fast build rule for target.
pfs_instr_class-oom-t/fast:
	$(MAKE) -f storage/perfschema/unittest/CMakeFiles/pfs_instr_class-oom-t.dir/build.make storage/perfschema/unittest/CMakeFiles/pfs_instr_class-oom-t.dir/build
.PHONY : pfs_instr_class-oom-t/fast

#=============================================================================
# Target rules for targets named pfs_instr_class-t

# Build rule for target.
pfs_instr_class-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs_instr_class-t
.PHONY : pfs_instr_class-t

# fast build rule for target.
pfs_instr_class-t/fast:
	$(MAKE) -f storage/perfschema/unittest/CMakeFiles/pfs_instr_class-t.dir/build.make storage/perfschema/unittest/CMakeFiles/pfs_instr_class-t.dir/build
.PHONY : pfs_instr_class-t/fast

#=============================================================================
# Target rules for targets named pfs_misc-t

# Build rule for target.
pfs_misc-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs_misc-t
.PHONY : pfs_misc-t

# fast build rule for target.
pfs_misc-t/fast:
	$(MAKE) -f storage/perfschema/unittest/CMakeFiles/pfs_misc-t.dir/build.make storage/perfschema/unittest/CMakeFiles/pfs_misc-t.dir/build
.PHONY : pfs_misc-t/fast

#=============================================================================
# Target rules for targets named pfs_noop-t

# Build rule for target.
pfs_noop-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs_noop-t
.PHONY : pfs_noop-t

# fast build rule for target.
pfs_noop-t/fast:
	$(MAKE) -f storage/perfschema/unittest/CMakeFiles/pfs_noop-t.dir/build.make storage/perfschema/unittest/CMakeFiles/pfs_noop-t.dir/build
.PHONY : pfs_noop-t/fast

#=============================================================================
# Target rules for targets named pfs_server_stubs

# Build rule for target.
pfs_server_stubs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs_server_stubs
.PHONY : pfs_server_stubs

# fast build rule for target.
pfs_server_stubs/fast:
	$(MAKE) -f storage/perfschema/unittest/CMakeFiles/pfs_server_stubs.dir/build.make storage/perfschema/unittest/CMakeFiles/pfs_server_stubs.dir/build
.PHONY : pfs_server_stubs/fast

#=============================================================================
# Target rules for targets named pfs_user-oom-t

# Build rule for target.
pfs_user-oom-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs_user-oom-t
.PHONY : pfs_user-oom-t

# fast build rule for target.
pfs_user-oom-t/fast:
	$(MAKE) -f storage/perfschema/unittest/CMakeFiles/pfs_user-oom-t.dir/build.make storage/perfschema/unittest/CMakeFiles/pfs_user-oom-t.dir/build
.PHONY : pfs_user-oom-t/fast

#=============================================================================
# Target rules for targets named myisam

# Build rule for target.
myisam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myisam
.PHONY : myisam

# fast build rule for target.
myisam/fast:
	$(MAKE) -f storage/myisam/CMakeFiles/myisam.dir/build.make storage/myisam/CMakeFiles/myisam.dir/build
.PHONY : myisam/fast

#=============================================================================
# Target rules for targets named myisam_embedded

# Build rule for target.
myisam_embedded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myisam_embedded
.PHONY : myisam_embedded

# fast build rule for target.
myisam_embedded/fast:
	$(MAKE) -f storage/myisam/CMakeFiles/myisam_embedded.dir/build.make storage/myisam/CMakeFiles/myisam_embedded.dir/build
.PHONY : myisam_embedded/fast

#=============================================================================
# Target rules for targets named myisam_ftdump

# Build rule for target.
myisam_ftdump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myisam_ftdump
.PHONY : myisam_ftdump

# fast build rule for target.
myisam_ftdump/fast:
	$(MAKE) -f storage/myisam/CMakeFiles/myisam_ftdump.dir/build.make storage/myisam/CMakeFiles/myisam_ftdump.dir/build
.PHONY : myisam_ftdump/fast

#=============================================================================
# Target rules for targets named myisamchk

# Build rule for target.
myisamchk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myisamchk
.PHONY : myisamchk

# fast build rule for target.
myisamchk/fast:
	$(MAKE) -f storage/myisam/CMakeFiles/myisamchk.dir/build.make storage/myisam/CMakeFiles/myisamchk.dir/build
.PHONY : myisamchk/fast

#=============================================================================
# Target rules for targets named myisamlog

# Build rule for target.
myisamlog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myisamlog
.PHONY : myisamlog

# fast build rule for target.
myisamlog/fast:
	$(MAKE) -f storage/myisam/CMakeFiles/myisamlog.dir/build.make storage/myisam/CMakeFiles/myisamlog.dir/build
.PHONY : myisamlog/fast

#=============================================================================
# Target rules for targets named myisampack

# Build rule for target.
myisampack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myisampack
.PHONY : myisampack

# fast build rule for target.
myisampack/fast:
	$(MAKE) -f storage/myisam/CMakeFiles/myisampack.dir/build.make storage/myisam/CMakeFiles/myisampack.dir/build
.PHONY : myisampack/fast

#=============================================================================
# Target rules for targets named partition

# Build rule for target.
partition: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 partition
.PHONY : partition

# fast build rule for target.
partition/fast:
	$(MAKE) -f storage/partition/CMakeFiles/partition.dir/build.make storage/partition/CMakeFiles/partition.dir/build
.PHONY : partition/fast

#=============================================================================
# Target rules for targets named partition_embedded

# Build rule for target.
partition_embedded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 partition_embedded
.PHONY : partition_embedded

# fast build rule for target.
partition_embedded/fast:
	$(MAKE) -f storage/partition/CMakeFiles/partition_embedded.dir/build.make storage/partition/CMakeFiles/partition_embedded.dir/build
.PHONY : partition_embedded/fast

#=============================================================================
# Target rules for targets named federated

# Build rule for target.
federated: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 federated
.PHONY : federated

# fast build rule for target.
federated/fast:
	$(MAKE) -f storage/federated/CMakeFiles/federated.dir/build.make storage/federated/CMakeFiles/federated.dir/build
.PHONY : federated/fast

#=============================================================================
# Target rules for targets named federated_embedded

# Build rule for target.
federated_embedded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 federated_embedded
.PHONY : federated_embedded

# fast build rule for target.
federated_embedded/fast:
	$(MAKE) -f storage/federated/CMakeFiles/federated_embedded.dir/build.make storage/federated/CMakeFiles/federated_embedded.dir/build
.PHONY : federated_embedded/fast

#=============================================================================
# Target rules for targets named myisammrg

# Build rule for target.
myisammrg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myisammrg
.PHONY : myisammrg

# fast build rule for target.
myisammrg/fast:
	$(MAKE) -f storage/myisammrg/CMakeFiles/myisammrg.dir/build.make storage/myisammrg/CMakeFiles/myisammrg.dir/build
.PHONY : myisammrg/fast

#=============================================================================
# Target rules for targets named myisammrg_embedded

# Build rule for target.
myisammrg_embedded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myisammrg_embedded
.PHONY : myisammrg_embedded

# fast build rule for target.
myisammrg_embedded/fast:
	$(MAKE) -f storage/myisammrg/CMakeFiles/myisammrg_embedded.dir/build.make storage/myisammrg/CMakeFiles/myisammrg_embedded.dir/build
.PHONY : myisammrg_embedded/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f storage/example/CMakeFiles/example.dir/build.make storage/example/CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named archive

# Build rule for target.
archive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 archive
.PHONY : archive

# fast build rule for target.
archive/fast:
	$(MAKE) -f storage/archive/CMakeFiles/archive.dir/build.make storage/archive/CMakeFiles/archive.dir/build
.PHONY : archive/fast

#=============================================================================
# Target rules for targets named heap

# Build rule for target.
heap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heap
.PHONY : heap

# fast build rule for target.
heap/fast:
	$(MAKE) -f storage/heap/CMakeFiles/heap.dir/build.make storage/heap/CMakeFiles/heap.dir/build
.PHONY : heap/fast

#=============================================================================
# Target rules for targets named heap_embedded

# Build rule for target.
heap_embedded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heap_embedded
.PHONY : heap_embedded

# fast build rule for target.
heap_embedded/fast:
	$(MAKE) -f storage/heap/CMakeFiles/heap_embedded.dir/build.make storage/heap/CMakeFiles/heap_embedded.dir/build
.PHONY : heap_embedded/fast

#=============================================================================
# Target rules for targets named hp_test1

# Build rule for target.
hp_test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hp_test1
.PHONY : hp_test1

# fast build rule for target.
hp_test1/fast:
	$(MAKE) -f storage/heap/CMakeFiles/hp_test1.dir/build.make storage/heap/CMakeFiles/hp_test1.dir/build
.PHONY : hp_test1/fast

#=============================================================================
# Target rules for targets named hp_test2

# Build rule for target.
hp_test2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hp_test2
.PHONY : hp_test2

# fast build rule for target.
hp_test2/fast:
	$(MAKE) -f storage/heap/CMakeFiles/hp_test2.dir/build.make storage/heap/CMakeFiles/hp_test2.dir/build
.PHONY : hp_test2/fast

#=============================================================================
# Target rules for targets named innobase

# Build rule for target.
innobase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 innobase
.PHONY : innobase

# fast build rule for target.
innobase/fast:
	$(MAKE) -f storage/innobase/CMakeFiles/innobase.dir/build.make storage/innobase/CMakeFiles/innobase.dir/build
.PHONY : innobase/fast

#=============================================================================
# Target rules for targets named blackhole

# Build rule for target.
blackhole: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blackhole
.PHONY : blackhole

# fast build rule for target.
blackhole/fast:
	$(MAKE) -f storage/blackhole/CMakeFiles/blackhole.dir/build.make storage/blackhole/CMakeFiles/blackhole.dir/build
.PHONY : blackhole/fast

#=============================================================================
# Target rules for targets named blackhole_embedded

# Build rule for target.
blackhole_embedded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blackhole_embedded
.PHONY : blackhole_embedded

# fast build rule for target.
blackhole_embedded/fast:
	$(MAKE) -f storage/blackhole/CMakeFiles/blackhole_embedded.dir/build.make storage/blackhole/CMakeFiles/blackhole_embedded.dir/build
.PHONY : blackhole_embedded/fast

#=============================================================================
# Target rules for targets named csv

# Build rule for target.
csv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csv
.PHONY : csv

# fast build rule for target.
csv/fast:
	$(MAKE) -f storage/csv/CMakeFiles/csv.dir/build.make storage/csv/CMakeFiles/csv.dir/build
.PHONY : csv/fast

#=============================================================================
# Target rules for targets named audit_null

# Build rule for target.
audit_null: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audit_null
.PHONY : audit_null

# fast build rule for target.
audit_null/fast:
	$(MAKE) -f plugin/audit_null/CMakeFiles/audit_null.dir/build.make plugin/audit_null/CMakeFiles/audit_null.dir/build
.PHONY : audit_null/fast

#=============================================================================
# Target rules for targets named test_security_context

# Build rule for target.
test_security_context: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_security_context
.PHONY : test_security_context

# fast build rule for target.
test_security_context/fast:
	$(MAKE) -f plugin/audit_null/CMakeFiles/test_security_context.dir/build.make plugin/audit_null/CMakeFiles/test_security_context.dir/build
.PHONY : test_security_context/fast

#=============================================================================
# Target rules for targets named rewrite_example

# Build rule for target.
rewrite_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rewrite_example
.PHONY : rewrite_example

# fast build rule for target.
rewrite_example/fast:
	$(MAKE) -f plugin/rewrite_example/CMakeFiles/rewrite_example.dir/build.make plugin/rewrite_example/CMakeFiles/rewrite_example.dir/build
.PHONY : rewrite_example/fast

#=============================================================================
# Target rules for targets named ftexample

# Build rule for target.
ftexample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ftexample
.PHONY : ftexample

# fast build rule for target.
ftexample/fast:
	$(MAKE) -f plugin/fulltext/CMakeFiles/ftexample.dir/build.make plugin/fulltext/CMakeFiles/ftexample.dir/build
.PHONY : ftexample/fast

#=============================================================================
# Target rules for targets named ngram_parser

# Build rule for target.
ngram_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ngram_parser
.PHONY : ngram_parser

# fast build rule for target.
ngram_parser/fast:
	$(MAKE) -f plugin/fulltext/CMakeFiles/ngram_parser.dir/build.make plugin/fulltext/CMakeFiles/ngram_parser.dir/build
.PHONY : ngram_parser/fast

#=============================================================================
# Target rules for targets named validate_password

# Build rule for target.
validate_password: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 validate_password
.PHONY : validate_password

# fast build rule for target.
validate_password/fast:
	$(MAKE) -f plugin/password_validation/CMakeFiles/validate_password.dir/build.make plugin/password_validation/CMakeFiles/validate_password.dir/build
.PHONY : validate_password/fast

#=============================================================================
# Target rules for targets named replication_observers_example

# Build rule for target.
replication_observers_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 replication_observers_example
.PHONY : replication_observers_example

# fast build rule for target.
replication_observers_example/fast:
	$(MAKE) -f plugin/replication_observers_example/CMakeFiles/replication_observers_example.dir/build.make plugin/replication_observers_example/CMakeFiles/replication_observers_example.dir/build
.PHONY : replication_observers_example/fast

#=============================================================================
# Target rules for targets named auth

# Build rule for target.
auth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 auth
.PHONY : auth

# fast build rule for target.
auth/fast:
	$(MAKE) -f plugin/auth/CMakeFiles/auth.dir/build.make plugin/auth/CMakeFiles/auth.dir/build
.PHONY : auth/fast

#=============================================================================
# Target rules for targets named auth_socket

# Build rule for target.
auth_socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 auth_socket
.PHONY : auth_socket

# fast build rule for target.
auth_socket/fast:
	$(MAKE) -f plugin/auth/CMakeFiles/auth_socket.dir/build.make plugin/auth/CMakeFiles/auth_socket.dir/build
.PHONY : auth_socket/fast

#=============================================================================
# Target rules for targets named auth_test_plugin

# Build rule for target.
auth_test_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 auth_test_plugin
.PHONY : auth_test_plugin

# fast build rule for target.
auth_test_plugin/fast:
	$(MAKE) -f plugin/auth/CMakeFiles/auth_test_plugin.dir/build.make plugin/auth/CMakeFiles/auth_test_plugin.dir/build
.PHONY : auth_test_plugin/fast

#=============================================================================
# Target rules for targets named mysql_no_login

# Build rule for target.
mysql_no_login: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql_no_login
.PHONY : mysql_no_login

# fast build rule for target.
mysql_no_login/fast:
	$(MAKE) -f plugin/auth/CMakeFiles/mysql_no_login.dir/build.make plugin/auth/CMakeFiles/mysql_no_login.dir/build
.PHONY : mysql_no_login/fast

#=============================================================================
# Target rules for targets named qa_auth_client

# Build rule for target.
qa_auth_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qa_auth_client
.PHONY : qa_auth_client

# fast build rule for target.
qa_auth_client/fast:
	$(MAKE) -f plugin/auth/CMakeFiles/qa_auth_client.dir/build.make plugin/auth/CMakeFiles/qa_auth_client.dir/build
.PHONY : qa_auth_client/fast

#=============================================================================
# Target rules for targets named qa_auth_interface

# Build rule for target.
qa_auth_interface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qa_auth_interface
.PHONY : qa_auth_interface

# fast build rule for target.
qa_auth_interface/fast:
	$(MAKE) -f plugin/auth/CMakeFiles/qa_auth_interface.dir/build.make plugin/auth/CMakeFiles/qa_auth_interface.dir/build
.PHONY : qa_auth_interface/fast

#=============================================================================
# Target rules for targets named qa_auth_server

# Build rule for target.
qa_auth_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qa_auth_server
.PHONY : qa_auth_server

# fast build rule for target.
qa_auth_server/fast:
	$(MAKE) -f plugin/auth/CMakeFiles/qa_auth_server.dir/build.make plugin/auth/CMakeFiles/qa_auth_server.dir/build
.PHONY : qa_auth_server/fast

#=============================================================================
# Target rules for targets named test_session_detach

# Build rule for target.
test_session_detach: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_session_detach
.PHONY : test_session_detach

# fast build rule for target.
test_session_detach/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_session_detach.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_session_detach.dir/build
.PHONY : test_session_detach/fast

#=============================================================================
# Target rules for targets named test_session_in_thd

# Build rule for target.
test_session_in_thd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_session_in_thd
.PHONY : test_session_in_thd

# fast build rule for target.
test_session_in_thd/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_session_in_thd.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_session_in_thd.dir/build
.PHONY : test_session_in_thd/fast

#=============================================================================
# Target rules for targets named test_session_info

# Build rule for target.
test_session_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_session_info
.PHONY : test_session_info

# fast build rule for target.
test_session_info/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_session_info.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_session_info.dir/build
.PHONY : test_session_info/fast

#=============================================================================
# Target rules for targets named test_sql_2_sessions

# Build rule for target.
test_sql_2_sessions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_2_sessions
.PHONY : test_sql_2_sessions

# fast build rule for target.
test_sql_2_sessions/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_2_sessions.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_2_sessions.dir/build
.PHONY : test_sql_2_sessions/fast

#=============================================================================
# Target rules for targets named test_sql_all_col_types

# Build rule for target.
test_sql_all_col_types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_all_col_types
.PHONY : test_sql_all_col_types

# fast build rule for target.
test_sql_all_col_types/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_all_col_types.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_all_col_types.dir/build
.PHONY : test_sql_all_col_types/fast

#=============================================================================
# Target rules for targets named test_sql_cmds_1

# Build rule for target.
test_sql_cmds_1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_cmds_1
.PHONY : test_sql_cmds_1

# fast build rule for target.
test_sql_cmds_1/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_cmds_1.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_cmds_1.dir/build
.PHONY : test_sql_cmds_1/fast

#=============================================================================
# Target rules for targets named test_sql_commit

# Build rule for target.
test_sql_commit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_commit
.PHONY : test_sql_commit

# fast build rule for target.
test_sql_commit/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_commit.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_commit.dir/build
.PHONY : test_sql_commit/fast

#=============================================================================
# Target rules for targets named test_sql_complex

# Build rule for target.
test_sql_complex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_complex
.PHONY : test_sql_complex

# fast build rule for target.
test_sql_complex/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_complex.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_complex.dir/build
.PHONY : test_sql_complex/fast

#=============================================================================
# Target rules for targets named test_sql_errors

# Build rule for target.
test_sql_errors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_errors
.PHONY : test_sql_errors

# fast build rule for target.
test_sql_errors/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_errors.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_errors.dir/build
.PHONY : test_sql_errors/fast

#=============================================================================
# Target rules for targets named test_sql_lock

# Build rule for target.
test_sql_lock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_lock
.PHONY : test_sql_lock

# fast build rule for target.
test_sql_lock/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_lock.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_lock.dir/build
.PHONY : test_sql_lock/fast

#=============================================================================
# Target rules for targets named test_sql_processlist

# Build rule for target.
test_sql_processlist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_processlist
.PHONY : test_sql_processlist

# fast build rule for target.
test_sql_processlist/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_processlist.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_processlist.dir/build
.PHONY : test_sql_processlist/fast

#=============================================================================
# Target rules for targets named test_sql_replication

# Build rule for target.
test_sql_replication: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_replication
.PHONY : test_sql_replication

# fast build rule for target.
test_sql_replication/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_replication.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_replication.dir/build
.PHONY : test_sql_replication/fast

#=============================================================================
# Target rules for targets named test_sql_shutdown

# Build rule for target.
test_sql_shutdown: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_shutdown
.PHONY : test_sql_shutdown

# fast build rule for target.
test_sql_shutdown/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_shutdown.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_shutdown.dir/build
.PHONY : test_sql_shutdown/fast

#=============================================================================
# Target rules for targets named test_sql_sqlmode

# Build rule for target.
test_sql_sqlmode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_sqlmode
.PHONY : test_sql_sqlmode

# fast build rule for target.
test_sql_sqlmode/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_sqlmode.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_sqlmode.dir/build
.PHONY : test_sql_sqlmode/fast

#=============================================================================
# Target rules for targets named test_sql_stored_procedures_functions

# Build rule for target.
test_sql_stored_procedures_functions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_stored_procedures_functions
.PHONY : test_sql_stored_procedures_functions

# fast build rule for target.
test_sql_stored_procedures_functions/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_stored_procedures_functions.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_stored_procedures_functions.dir/build
.PHONY : test_sql_stored_procedures_functions/fast

#=============================================================================
# Target rules for targets named test_sql_views_triggers

# Build rule for target.
test_sql_views_triggers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sql_views_triggers
.PHONY : test_sql_views_triggers

# fast build rule for target.
test_sql_views_triggers/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_sql_views_triggers.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_sql_views_triggers.dir/build
.PHONY : test_sql_views_triggers/fast

#=============================================================================
# Target rules for targets named test_x_sessions_deinit

# Build rule for target.
test_x_sessions_deinit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_x_sessions_deinit
.PHONY : test_x_sessions_deinit

# fast build rule for target.
test_x_sessions_deinit/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_x_sessions_deinit.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_x_sessions_deinit.dir/build
.PHONY : test_x_sessions_deinit/fast

#=============================================================================
# Target rules for targets named test_x_sessions_init

# Build rule for target.
test_x_sessions_init: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_x_sessions_init
.PHONY : test_x_sessions_init

# fast build rule for target.
test_x_sessions_init/fast:
	$(MAKE) -f plugin/test_service_sql_api/CMakeFiles/test_x_sessions_init.dir/build.make plugin/test_service_sql_api/CMakeFiles/test_x_sessions_init.dir/build
.PHONY : test_x_sessions_init/fast

#=============================================================================
# Target rules for targets named daemon_example

# Build rule for target.
daemon_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daemon_example
.PHONY : daemon_example

# fast build rule for target.
daemon_example/fast:
	$(MAKE) -f plugin/daemon_example/CMakeFiles/daemon_example.dir/build.make plugin/daemon_example/CMakeFiles/daemon_example.dir/build
.PHONY : daemon_example/fast

#=============================================================================
# Target rules for targets named semisync_master

# Build rule for target.
semisync_master: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 semisync_master
.PHONY : semisync_master

# fast build rule for target.
semisync_master/fast:
	$(MAKE) -f plugin/semisync/CMakeFiles/semisync_master.dir/build.make plugin/semisync/CMakeFiles/semisync_master.dir/build
.PHONY : semisync_master/fast

#=============================================================================
# Target rules for targets named semisync_slave

# Build rule for target.
semisync_slave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 semisync_slave
.PHONY : semisync_slave

# fast build rule for target.
semisync_slave/fast:
	$(MAKE) -f plugin/semisync/CMakeFiles/semisync_slave.dir/build.make plugin/semisync/CMakeFiles/semisync_slave.dir/build
.PHONY : semisync_slave/fast

#=============================================================================
# Target rules for targets named version_token

# Build rule for target.
version_token: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version_token
.PHONY : version_token

# fast build rule for target.
version_token/fast:
	$(MAKE) -f plugin/version_token/CMakeFiles/version_token.dir/build.make plugin/version_token/CMakeFiles/version_token.dir/build
.PHONY : version_token/fast

#=============================================================================
# Target rules for targets named test_framework

# Build rule for target.
test_framework: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_framework
.PHONY : test_framework

# fast build rule for target.
test_framework/fast:
	$(MAKE) -f plugin/test_services/CMakeFiles/test_framework.dir/build.make plugin/test_services/CMakeFiles/test_framework.dir/build
.PHONY : test_framework/fast

#=============================================================================
# Target rules for targets named test_services

# Build rule for target.
test_services: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_services
.PHONY : test_services

# fast build rule for target.
test_services/fast:
	$(MAKE) -f plugin/test_services/CMakeFiles/test_services.dir/build.make plugin/test_services/CMakeFiles/test_services.dir/build
.PHONY : test_services/fast

#=============================================================================
# Target rules for targets named test_services_thread

# Build rule for target.
test_services_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_services_thread
.PHONY : test_services_thread

# fast build rule for target.
test_services_thread/fast:
	$(MAKE) -f plugin/test_services/CMakeFiles/test_services_thread.dir/build.make plugin/test_services/CMakeFiles/test_services_thread.dir/build
.PHONY : test_services_thread/fast

#=============================================================================
# Target rules for targets named rewriter

# Build rule for target.
rewriter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rewriter
.PHONY : rewriter

# fast build rule for target.
rewriter/fast:
	$(MAKE) -f plugin/rewriter/CMakeFiles/rewriter.dir/build.make plugin/rewriter/CMakeFiles/rewriter.dir/build
.PHONY : rewriter/fast

#=============================================================================
# Target rules for targets named dbug

# Build rule for target.
dbug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dbug
.PHONY : dbug

# fast build rule for target.
dbug/fast:
	$(MAKE) -f dbug/CMakeFiles/dbug.dir/build.make dbug/CMakeFiles/dbug.dir/build
.PHONY : dbug/fast

#=============================================================================
# Target rules for targets named conf_to_src

# Build rule for target.
conf_to_src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 conf_to_src
.PHONY : conf_to_src

# fast build rule for target.
conf_to_src/fast:
	$(MAKE) -f strings/CMakeFiles/conf_to_src.dir/build.make strings/CMakeFiles/conf_to_src.dir/build
.PHONY : conf_to_src/fast

#=============================================================================
# Target rules for targets named strings

# Build rule for target.
strings: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strings
.PHONY : strings

# fast build rule for target.
strings/fast:
	$(MAKE) -f strings/CMakeFiles/strings.dir/build.make strings/CMakeFiles/strings.dir/build
.PHONY : strings/fast

#=============================================================================
# Target rules for targets named vio

# Build rule for target.
vio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vio
.PHONY : vio

# fast build rule for target.
vio/fast:
	$(MAKE) -f vio/CMakeFiles/vio.dir/build.make vio/CMakeFiles/vio.dir/build
.PHONY : vio/fast

#=============================================================================
# Target rules for targets named re

# Build rule for target.
re: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 re
.PHONY : re

# fast build rule for target.
re/fast:
	$(MAKE) -f regex/CMakeFiles/re.dir/build.make regex/CMakeFiles/re.dir/build
.PHONY : re/fast

#=============================================================================
# Target rules for targets named regex

# Build rule for target.
regex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 regex
.PHONY : regex

# fast build rule for target.
regex/fast:
	$(MAKE) -f regex/CMakeFiles/regex.dir/build.make regex/CMakeFiles/regex.dir/build
.PHONY : regex/fast

#=============================================================================
# Target rules for targets named base64_test

# Build rule for target.
base64_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 base64_test
.PHONY : base64_test

# fast build rule for target.
base64_test/fast:
	$(MAKE) -f mysys/CMakeFiles/base64_test.dir/build.make mysys/CMakeFiles/base64_test.dir/build
.PHONY : base64_test/fast

#=============================================================================
# Target rules for targets named mysys

# Build rule for target.
mysys: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysys
.PHONY : mysys

# fast build rule for target.
mysys/fast:
	$(MAKE) -f mysys/CMakeFiles/mysys.dir/build.make mysys/CMakeFiles/mysys.dir/build
.PHONY : mysys/fast

#=============================================================================
# Target rules for targets named queues

# Build rule for target.
queues: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 queues
.PHONY : queues

# fast build rule for target.
queues/fast:
	$(MAKE) -f mysys/CMakeFiles/queues.dir/build.make mysys/CMakeFiles/queues.dir/build
.PHONY : queues/fast

#=============================================================================
# Target rules for targets named thr_lock

# Build rule for target.
thr_lock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thr_lock
.PHONY : thr_lock

# fast build rule for target.
thr_lock/fast:
	$(MAKE) -f mysys/CMakeFiles/thr_lock.dir/build.make mysys/CMakeFiles/thr_lock.dir/build
.PHONY : thr_lock/fast

#=============================================================================
# Target rules for targets named mysys_ssl

# Build rule for target.
mysys_ssl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysys_ssl
.PHONY : mysys_ssl

# fast build rule for target.
mysys_ssl/fast:
	$(MAKE) -f mysys_ssl/CMakeFiles/mysys_ssl.dir/build.make mysys_ssl/CMakeFiles/mysys_ssl.dir/build
.PHONY : mysys_ssl/fast

#=============================================================================
# Target rules for targets named clientlib

# Build rule for target.
clientlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clientlib
.PHONY : clientlib

# fast build rule for target.
clientlib/fast:
	$(MAKE) -f libmysql/CMakeFiles/clientlib.dir/build.make libmysql/CMakeFiles/clientlib.dir/build
.PHONY : clientlib/fast

#=============================================================================
# Target rules for targets named libmysql

# Build rule for target.
libmysql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libmysql
.PHONY : libmysql

# fast build rule for target.
libmysql/fast:
	$(MAKE) -f libmysql/CMakeFiles/libmysql.dir/build.make libmysql/CMakeFiles/libmysql.dir/build
.PHONY : libmysql/fast

#=============================================================================
# Target rules for targets named libmysql_api_test

# Build rule for target.
libmysql_api_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libmysql_api_test
.PHONY : libmysql_api_test

# fast build rule for target.
libmysql_api_test/fast:
	$(MAKE) -f libmysql/CMakeFiles/libmysql_api_test.dir/build.make libmysql/CMakeFiles/libmysql_api_test.dir/build
.PHONY : libmysql_api_test/fast

#=============================================================================
# Target rules for targets named mysqlclient

# Build rule for target.
mysqlclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlclient
.PHONY : mysqlclient

# fast build rule for target.
mysqlclient/fast:
	$(MAKE) -f libmysql/CMakeFiles/mysqlclient.dir/build.make libmysql/CMakeFiles/mysqlclient.dir/build
.PHONY : mysqlclient/fast

#=============================================================================
# Target rules for targets named binlogevents_static

# Build rule for target.
binlogevents_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binlogevents_static
.PHONY : binlogevents_static

# fast build rule for target.
binlogevents_static/fast:
	$(MAKE) -f libbinlogevents/src/CMakeFiles/binlogevents_static.dir/build.make libbinlogevents/src/CMakeFiles/binlogevents_static.dir/build
.PHONY : binlogevents_static/fast

#=============================================================================
# Target rules for targets named binlogstandalone_shared

# Build rule for target.
binlogstandalone_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binlogstandalone_shared
.PHONY : binlogstandalone_shared

# fast build rule for target.
binlogstandalone_shared/fast:
	$(MAKE) -f libbinlogstandalone/src/CMakeFiles/binlogstandalone_shared.dir/build.make libbinlogstandalone/src/CMakeFiles/binlogstandalone_shared.dir/build
.PHONY : binlogstandalone_shared/fast

#=============================================================================
# Target rules for targets named binlogstandalone_static

# Build rule for target.
binlogstandalone_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binlogstandalone_static
.PHONY : binlogstandalone_static

# fast build rule for target.
binlogstandalone_static/fast:
	$(MAKE) -f libbinlogstandalone/src/CMakeFiles/binlogstandalone_static.dir/build.make libbinlogstandalone/src/CMakeFiles/binlogstandalone_static.dir/build
.PHONY : binlogstandalone_static/fast

#=============================================================================
# Target rules for targets named test-unit

# Build rule for target.
test-unit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-unit
.PHONY : test-unit

# fast build rule for target.
test-unit/fast:
	$(MAKE) -f unittest/CMakeFiles/test-unit.dir/build.make unittest/CMakeFiles/test-unit.dir/build
.PHONY : test-unit/fast

#=============================================================================
# Target rules for targets named no_plan-t

# Build rule for target.
no_plan-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 no_plan-t
.PHONY : no_plan-t

# fast build rule for target.
no_plan-t/fast:
	$(MAKE) -f unittest/examples/CMakeFiles/no_plan-t.dir/build.make unittest/examples/CMakeFiles/no_plan-t.dir/build
.PHONY : no_plan-t/fast

#=============================================================================
# Target rules for targets named simple-t

# Build rule for target.
simple-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple-t
.PHONY : simple-t

# fast build rule for target.
simple-t/fast:
	$(MAKE) -f unittest/examples/CMakeFiles/simple-t.dir/build.make unittest/examples/CMakeFiles/simple-t.dir/build
.PHONY : simple-t/fast

#=============================================================================
# Target rules for targets named skip-t

# Build rule for target.
skip-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 skip-t
.PHONY : skip-t

# fast build rule for target.
skip-t/fast:
	$(MAKE) -f unittest/examples/CMakeFiles/skip-t.dir/build.make unittest/examples/CMakeFiles/skip-t.dir/build
.PHONY : skip-t/fast

#=============================================================================
# Target rules for targets named skip_all-t

# Build rule for target.
skip_all-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 skip_all-t
.PHONY : skip_all-t

# fast build rule for target.
skip_all-t/fast:
	$(MAKE) -f unittest/examples/CMakeFiles/skip_all-t.dir/build.make unittest/examples/CMakeFiles/skip_all-t.dir/build
.PHONY : skip_all-t/fast

#=============================================================================
# Target rules for targets named todo-t

# Build rule for target.
todo-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 todo-t
.PHONY : todo-t

# fast build rule for target.
todo-t/fast:
	$(MAKE) -f unittest/examples/CMakeFiles/todo-t.dir/build.make unittest/examples/CMakeFiles/todo-t.dir/build
.PHONY : todo-t/fast

#=============================================================================
# Target rules for targets named mytap

# Build rule for target.
mytap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mytap
.PHONY : mytap

# fast build rule for target.
mytap/fast:
	$(MAKE) -f unittest/mytap/CMakeFiles/mytap.dir/build.make unittest/mytap/CMakeFiles/mytap.dir/build
.PHONY : mytap/fast

#=============================================================================
# Target rules for targets named basic-t

# Build rule for target.
basic-t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic-t
.PHONY : basic-t

# fast build rule for target.
basic-t/fast:
	$(MAKE) -f unittest/mytap/t/CMakeFiles/basic-t.dir/build.make unittest/mytap/t/CMakeFiles/basic-t.dir/build
.PHONY : basic-t/fast

#=============================================================================
# Target rules for targets named GenError

# Build rule for target.
GenError: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GenError
.PHONY : GenError

# fast build rule for target.
GenError/fast:
	$(MAKE) -f extra/CMakeFiles/GenError.dir/build.make extra/CMakeFiles/GenError.dir/build
.PHONY : GenError/fast

#=============================================================================
# Target rules for targets named comp_err

# Build rule for target.
comp_err: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comp_err
.PHONY : comp_err

# fast build rule for target.
comp_err/fast:
	$(MAKE) -f extra/CMakeFiles/comp_err.dir/build.make extra/CMakeFiles/comp_err.dir/build
.PHONY : comp_err/fast

#=============================================================================
# Target rules for targets named innochecksum

# Build rule for target.
innochecksum: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 innochecksum
.PHONY : innochecksum

# fast build rule for target.
innochecksum/fast:
	$(MAKE) -f extra/CMakeFiles/innochecksum.dir/build.make extra/CMakeFiles/innochecksum.dir/build
.PHONY : innochecksum/fast

#=============================================================================
# Target rules for targets named lz4_lib

# Build rule for target.
lz4_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lz4_lib
.PHONY : lz4_lib

# fast build rule for target.
lz4_lib/fast:
	$(MAKE) -f extra/CMakeFiles/lz4_lib.dir/build.make extra/CMakeFiles/lz4_lib.dir/build
.PHONY : lz4_lib/fast

#=============================================================================
# Target rules for targets named my_print_defaults

# Build rule for target.
my_print_defaults: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_print_defaults
.PHONY : my_print_defaults

# fast build rule for target.
my_print_defaults/fast:
	$(MAKE) -f extra/CMakeFiles/my_print_defaults.dir/build.make extra/CMakeFiles/my_print_defaults.dir/build
.PHONY : my_print_defaults/fast

#=============================================================================
# Target rules for targets named perror

# Build rule for target.
perror: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perror
.PHONY : perror

# fast build rule for target.
perror/fast:
	$(MAKE) -f extra/CMakeFiles/perror.dir/build.make extra/CMakeFiles/perror.dir/build
.PHONY : perror/fast

#=============================================================================
# Target rules for targets named replace

# Build rule for target.
replace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 replace
.PHONY : replace

# fast build rule for target.
replace/fast:
	$(MAKE) -f extra/CMakeFiles/replace.dir/build.make extra/CMakeFiles/replace.dir/build
.PHONY : replace/fast

#=============================================================================
# Target rules for targets named resolve_stack_dump

# Build rule for target.
resolve_stack_dump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 resolve_stack_dump
.PHONY : resolve_stack_dump

# fast build rule for target.
resolve_stack_dump/fast:
	$(MAKE) -f extra/CMakeFiles/resolve_stack_dump.dir/build.make extra/CMakeFiles/resolve_stack_dump.dir/build
.PHONY : resolve_stack_dump/fast

#=============================================================================
# Target rules for targets named resolveip

# Build rule for target.
resolveip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 resolveip
.PHONY : resolveip

# fast build rule for target.
resolveip/fast:
	$(MAKE) -f extra/CMakeFiles/resolveip.dir/build.make extra/CMakeFiles/resolveip.dir/build
.PHONY : resolveip/fast

#=============================================================================
# Target rules for targets named boost_lib

# Build rule for target.
boost_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boost_lib
.PHONY : boost_lib

# fast build rule for target.
boost_lib/fast:
	$(MAKE) -f client/CMakeFiles/boost_lib.dir/build.make client/CMakeFiles/boost_lib.dir/build
.PHONY : boost_lib/fast

#=============================================================================
# Target rules for targets named mysql

# Build rule for target.
mysql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql
.PHONY : mysql

# fast build rule for target.
mysql/fast:
	$(MAKE) -f client/CMakeFiles/mysql.dir/build.make client/CMakeFiles/mysql.dir/build
.PHONY : mysql/fast

#=============================================================================
# Target rules for targets named mysql_config_editor

# Build rule for target.
mysql_config_editor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql_config_editor
.PHONY : mysql_config_editor

# fast build rule for target.
mysql_config_editor/fast:
	$(MAKE) -f client/CMakeFiles/mysql_config_editor.dir/build.make client/CMakeFiles/mysql_config_editor.dir/build
.PHONY : mysql_config_editor/fast

#=============================================================================
# Target rules for targets named mysql_install_db

# Build rule for target.
mysql_install_db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql_install_db
.PHONY : mysql_install_db

# fast build rule for target.
mysql_install_db/fast:
	$(MAKE) -f client/CMakeFiles/mysql_install_db.dir/build.make client/CMakeFiles/mysql_install_db.dir/build
.PHONY : mysql_install_db/fast

#=============================================================================
# Target rules for targets named mysql_plugin

# Build rule for target.
mysql_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql_plugin
.PHONY : mysql_plugin

# fast build rule for target.
mysql_plugin/fast:
	$(MAKE) -f client/CMakeFiles/mysql_plugin.dir/build.make client/CMakeFiles/mysql_plugin.dir/build
.PHONY : mysql_plugin/fast

#=============================================================================
# Target rules for targets named mysql_secure_installation

# Build rule for target.
mysql_secure_installation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql_secure_installation
.PHONY : mysql_secure_installation

# fast build rule for target.
mysql_secure_installation/fast:
	$(MAKE) -f client/CMakeFiles/mysql_secure_installation.dir/build.make client/CMakeFiles/mysql_secure_installation.dir/build
.PHONY : mysql_secure_installation/fast

#=============================================================================
# Target rules for targets named mysql_ssl_rsa_setup

# Build rule for target.
mysql_ssl_rsa_setup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql_ssl_rsa_setup
.PHONY : mysql_ssl_rsa_setup

# fast build rule for target.
mysql_ssl_rsa_setup/fast:
	$(MAKE) -f client/CMakeFiles/mysql_ssl_rsa_setup.dir/build.make client/CMakeFiles/mysql_ssl_rsa_setup.dir/build
.PHONY : mysql_ssl_rsa_setup/fast

#=============================================================================
# Target rules for targets named mysql_upgrade

# Build rule for target.
mysql_upgrade: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql_upgrade
.PHONY : mysql_upgrade

# fast build rule for target.
mysql_upgrade/fast:
	$(MAKE) -f client/CMakeFiles/mysql_upgrade.dir/build.make client/CMakeFiles/mysql_upgrade.dir/build
.PHONY : mysql_upgrade/fast

#=============================================================================
# Target rules for targets named mysqladmin

# Build rule for target.
mysqladmin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqladmin
.PHONY : mysqladmin

# fast build rule for target.
mysqladmin/fast:
	$(MAKE) -f client/CMakeFiles/mysqladmin.dir/build.make client/CMakeFiles/mysqladmin.dir/build
.PHONY : mysqladmin/fast

#=============================================================================
# Target rules for targets named mysqlbinlog

# Build rule for target.
mysqlbinlog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlbinlog
.PHONY : mysqlbinlog

# fast build rule for target.
mysqlbinlog/fast:
	$(MAKE) -f client/CMakeFiles/mysqlbinlog.dir/build.make client/CMakeFiles/mysqlbinlog.dir/build
.PHONY : mysqlbinlog/fast

#=============================================================================
# Target rules for targets named mysqlcheck

# Build rule for target.
mysqlcheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlcheck
.PHONY : mysqlcheck

# fast build rule for target.
mysqlcheck/fast:
	$(MAKE) -f client/CMakeFiles/mysqlcheck.dir/build.make client/CMakeFiles/mysqlcheck.dir/build
.PHONY : mysqlcheck/fast

#=============================================================================
# Target rules for targets named mysqlcheck_core

# Build rule for target.
mysqlcheck_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlcheck_core
.PHONY : mysqlcheck_core

# fast build rule for target.
mysqlcheck_core/fast:
	$(MAKE) -f client/CMakeFiles/mysqlcheck_core.dir/build.make client/CMakeFiles/mysqlcheck_core.dir/build
.PHONY : mysqlcheck_core/fast

#=============================================================================
# Target rules for targets named mysqldump

# Build rule for target.
mysqldump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqldump
.PHONY : mysqldump

# fast build rule for target.
mysqldump/fast:
	$(MAKE) -f client/CMakeFiles/mysqldump.dir/build.make client/CMakeFiles/mysqldump.dir/build
.PHONY : mysqldump/fast

#=============================================================================
# Target rules for targets named mysqlimport

# Build rule for target.
mysqlimport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlimport
.PHONY : mysqlimport

# fast build rule for target.
mysqlimport/fast:
	$(MAKE) -f client/CMakeFiles/mysqlimport.dir/build.make client/CMakeFiles/mysqlimport.dir/build
.PHONY : mysqlimport/fast

#=============================================================================
# Target rules for targets named mysqlshow

# Build rule for target.
mysqlshow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlshow
.PHONY : mysqlshow

# fast build rule for target.
mysqlshow/fast:
	$(MAKE) -f client/CMakeFiles/mysqlshow.dir/build.make client/CMakeFiles/mysqlshow.dir/build
.PHONY : mysqlshow/fast

#=============================================================================
# Target rules for targets named mysqlslap

# Build rule for target.
mysqlslap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlslap
.PHONY : mysqlslap

# fast build rule for target.
mysqlslap/fast:
	$(MAKE) -f client/CMakeFiles/mysqlslap.dir/build.make client/CMakeFiles/mysqlslap.dir/build
.PHONY : mysqlslap/fast

#=============================================================================
# Target rules for targets named mysqltest

# Build rule for target.
mysqltest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqltest
.PHONY : mysqltest

# fast build rule for target.
mysqltest/fast:
	$(MAKE) -f client/CMakeFiles/mysqltest.dir/build.make client/CMakeFiles/mysqltest.dir/build
.PHONY : mysqltest/fast

#=============================================================================
# Target rules for targets named client_base

# Build rule for target.
client_base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_base
.PHONY : client_base

# fast build rule for target.
client_base/fast:
	$(MAKE) -f client/base/CMakeFiles/client_base.dir/build.make client/base/CMakeFiles/client_base.dir/build
.PHONY : client_base/fast

#=============================================================================
# Target rules for targets named mysqlpump

# Build rule for target.
mysqlpump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlpump
.PHONY : mysqlpump

# fast build rule for target.
mysqlpump/fast:
	$(MAKE) -f client/dump/CMakeFiles/mysqlpump.dir/build.make client/dump/CMakeFiles/mysqlpump.dir/build
.PHONY : mysqlpump/fast

#=============================================================================
# Target rules for targets named mysqlpump_lib

# Build rule for target.
mysqlpump_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlpump_lib
.PHONY : mysqlpump_lib

# fast build rule for target.
mysqlpump_lib/fast:
	$(MAKE) -f client/dump/CMakeFiles/mysqlpump_lib.dir/build.make client/dump/CMakeFiles/mysqlpump_lib.dir/build
.PHONY : mysqlpump_lib/fast

#=============================================================================
# Target rules for targets named mysqlservices

# Build rule for target.
mysqlservices: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlservices
.PHONY : mysqlservices

# fast build rule for target.
mysqlservices/fast:
	$(MAKE) -f libservices/CMakeFiles/mysqlservices.dir/build.make libservices/CMakeFiles/mysqlservices.dir/build
.PHONY : mysqlservices/fast

#=============================================================================
# Target rules for targets named bug25714

# Build rule for target.
bug25714: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bug25714
.PHONY : bug25714

# fast build rule for target.
bug25714/fast:
	$(MAKE) -f testclients/CMakeFiles/bug25714.dir/build.make testclients/CMakeFiles/bug25714.dir/build
.PHONY : bug25714/fast

#=============================================================================
# Target rules for targets named mysql_client_test

# Build rule for target.
mysql_client_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql_client_test
.PHONY : mysql_client_test

# fast build rule for target.
mysql_client_test/fast:
	$(MAKE) -f testclients/CMakeFiles/mysql_client_test.dir/build.make testclients/CMakeFiles/mysql_client_test.dir/build
.PHONY : mysql_client_test/fast

#=============================================================================
# Target rules for targets named GenDigestServerSource

# Build rule for target.
GenDigestServerSource: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GenDigestServerSource
.PHONY : GenDigestServerSource

# fast build rule for target.
GenDigestServerSource/fast:
	$(MAKE) -f sql/CMakeFiles/GenDigestServerSource.dir/build.make sql/CMakeFiles/GenDigestServerSource.dir/build
.PHONY : GenDigestServerSource/fast

#=============================================================================
# Target rules for targets named GenServerSource

# Build rule for target.
GenServerSource: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GenServerSource
.PHONY : GenServerSource

# fast build rule for target.
GenServerSource/fast:
	$(MAKE) -f sql/CMakeFiles/GenServerSource.dir/build.make sql/CMakeFiles/GenServerSource.dir/build
.PHONY : GenServerSource/fast

#=============================================================================
# Target rules for targets named binlog

# Build rule for target.
binlog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binlog
.PHONY : binlog

# fast build rule for target.
binlog/fast:
	$(MAKE) -f sql/CMakeFiles/binlog.dir/build.make sql/CMakeFiles/binlog.dir/build
.PHONY : binlog/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f sql/CMakeFiles/dist.dir/build.make sql/CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) -f sql/CMakeFiles/distclean.dir/build.make sql/CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named gen_lex_hash

# Build rule for target.
gen_lex_hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_lex_hash
.PHONY : gen_lex_hash

# fast build rule for target.
gen_lex_hash/fast:
	$(MAKE) -f sql/CMakeFiles/gen_lex_hash.dir/build.make sql/CMakeFiles/gen_lex_hash.dir/build
.PHONY : gen_lex_hash/fast

#=============================================================================
# Target rules for targets named gen_lex_token

# Build rule for target.
gen_lex_token: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_lex_token
.PHONY : gen_lex_token

# fast build rule for target.
gen_lex_token/fast:
	$(MAKE) -f sql/CMakeFiles/gen_lex_token.dir/build.make sql/CMakeFiles/gen_lex_token.dir/build
.PHONY : gen_lex_token/fast

#=============================================================================
# Target rules for targets named locking_service

# Build rule for target.
locking_service: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 locking_service
.PHONY : locking_service

# fast build rule for target.
locking_service/fast:
	$(MAKE) -f sql/CMakeFiles/locking_service.dir/build.make sql/CMakeFiles/locking_service.dir/build
.PHONY : locking_service/fast

#=============================================================================
# Target rules for targets named master

# Build rule for target.
master: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 master
.PHONY : master

# fast build rule for target.
master/fast:
	$(MAKE) -f sql/CMakeFiles/master.dir/build.make sql/CMakeFiles/master.dir/build
.PHONY : master/fast

#=============================================================================
# Target rules for targets named mysql_tzinfo_to_sql

# Build rule for target.
mysql_tzinfo_to_sql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql_tzinfo_to_sql
.PHONY : mysql_tzinfo_to_sql

# fast build rule for target.
mysql_tzinfo_to_sql/fast:
	$(MAKE) -f sql/CMakeFiles/mysql_tzinfo_to_sql.dir/build.make sql/CMakeFiles/mysql_tzinfo_to_sql.dir/build
.PHONY : mysql_tzinfo_to_sql/fast

#=============================================================================
# Target rules for targets named mysqld

# Build rule for target.
mysqld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqld
.PHONY : mysqld

# fast build rule for target.
mysqld/fast:
	$(MAKE) -f sql/CMakeFiles/mysqld.dir/build.make sql/CMakeFiles/mysqld.dir/build
.PHONY : mysqld/fast

#=============================================================================
# Target rules for targets named rpl

# Build rule for target.
rpl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpl
.PHONY : rpl

# fast build rule for target.
rpl/fast:
	$(MAKE) -f sql/CMakeFiles/rpl.dir/build.make sql/CMakeFiles/rpl.dir/build
.PHONY : rpl/fast

#=============================================================================
# Target rules for targets named show-dist-name

# Build rule for target.
show-dist-name: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 show-dist-name
.PHONY : show-dist-name

# fast build rule for target.
show-dist-name/fast:
	$(MAKE) -f sql/CMakeFiles/show-dist-name.dir/build.make sql/CMakeFiles/show-dist-name.dir/build
.PHONY : show-dist-name/fast

#=============================================================================
# Target rules for targets named slave

# Build rule for target.
slave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slave
.PHONY : slave

# fast build rule for target.
slave/fast:
	$(MAKE) -f sql/CMakeFiles/slave.dir/build.make sql/CMakeFiles/slave.dir/build
.PHONY : slave/fast

#=============================================================================
# Target rules for targets named sql

# Build rule for target.
sql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sql
.PHONY : sql

# fast build rule for target.
sql/fast:
	$(MAKE) -f sql/CMakeFiles/sql.dir/build.make sql/CMakeFiles/sql.dir/build
.PHONY : sql/fast

#=============================================================================
# Target rules for targets named sqlgunitlib

# Build rule for target.
sqlgunitlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sqlgunitlib
.PHONY : sqlgunitlib

# fast build rule for target.
sqlgunitlib/fast:
	$(MAKE) -f sql/CMakeFiles/sqlgunitlib.dir/build.make sql/CMakeFiles/sqlgunitlib.dir/build
.PHONY : sqlgunitlib/fast

#=============================================================================
# Target rules for targets named udf_example

# Build rule for target.
udf_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udf_example
.PHONY : udf_example

# fast build rule for target.
udf_example/fast:
	$(MAKE) -f sql/CMakeFiles/udf_example.dir/build.make sql/CMakeFiles/udf_example.dir/build
.PHONY : udf_example/fast

#=============================================================================
# Target rules for targets named GenYaccEmbeddedSource

# Build rule for target.
GenYaccEmbeddedSource: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GenYaccEmbeddedSource
.PHONY : GenYaccEmbeddedSource

# fast build rule for target.
GenYaccEmbeddedSource/fast:
	$(MAKE) -f libmysqld/CMakeFiles/GenYaccEmbeddedSource.dir/build.make libmysqld/CMakeFiles/GenYaccEmbeddedSource.dir/build
.PHONY : GenYaccEmbeddedSource/fast

#=============================================================================
# Target rules for targets named mysqlserver

# Build rule for target.
mysqlserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlserver
.PHONY : mysqlserver

# fast build rule for target.
mysqlserver/fast:
	$(MAKE) -f libmysqld/CMakeFiles/mysqlserver.dir/build.make libmysqld/CMakeFiles/mysqlserver.dir/build
.PHONY : mysqlserver/fast

#=============================================================================
# Target rules for targets named sql_embedded

# Build rule for target.
sql_embedded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sql_embedded
.PHONY : sql_embedded

# fast build rule for target.
sql_embedded/fast:
	$(MAKE) -f libmysqld/CMakeFiles/sql_embedded.dir/build.make libmysqld/CMakeFiles/sql_embedded.dir/build
.PHONY : sql_embedded/fast

#=============================================================================
# Target rules for targets named mysql_client_test_embedded

# Build rule for target.
mysql_client_test_embedded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql_client_test_embedded
.PHONY : mysql_client_test_embedded

# fast build rule for target.
mysql_client_test_embedded/fast:
	$(MAKE) -f libmysqld/examples/CMakeFiles/mysql_client_test_embedded.dir/build.make libmysqld/examples/CMakeFiles/mysql_client_test_embedded.dir/build
.PHONY : mysql_client_test_embedded/fast

#=============================================================================
# Target rules for targets named mysql_embedded

# Build rule for target.
mysql_embedded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql_embedded
.PHONY : mysql_embedded

# fast build rule for target.
mysql_embedded/fast:
	$(MAKE) -f libmysqld/examples/CMakeFiles/mysql_embedded.dir/build.make libmysqld/examples/CMakeFiles/mysql_embedded.dir/build
.PHONY : mysql_embedded/fast

#=============================================================================
# Target rules for targets named mysqltest_embedded

# Build rule for target.
mysqltest_embedded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqltest_embedded
.PHONY : mysqltest_embedded

# fast build rule for target.
mysqltest_embedded/fast:
	$(MAKE) -f libmysqld/examples/CMakeFiles/mysqltest_embedded.dir/build.make libmysqld/examples/CMakeFiles/mysqltest_embedded.dir/build
.PHONY : mysqltest_embedded/fast

#=============================================================================
# Target rules for targets named GenBootstrapPriv

# Build rule for target.
GenBootstrapPriv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GenBootstrapPriv
.PHONY : GenBootstrapPriv

# fast build rule for target.
GenBootstrapPriv/fast:
	$(MAKE) -f scripts/CMakeFiles/GenBootstrapPriv.dir/build.make scripts/CMakeFiles/GenBootstrapPriv.dir/build
.PHONY : GenBootstrapPriv/fast

#=============================================================================
# Target rules for targets named GenFixPrivs

# Build rule for target.
GenFixPrivs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GenFixPrivs
.PHONY : GenFixPrivs

# fast build rule for target.
GenFixPrivs/fast:
	$(MAKE) -f scripts/CMakeFiles/GenFixPrivs.dir/build.make scripts/CMakeFiles/GenFixPrivs.dir/build
.PHONY : GenFixPrivs/fast

#=============================================================================
# Target rules for targets named GenSysSchema

# Build rule for target.
GenSysSchema: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GenSysSchema
.PHONY : GenSysSchema

# fast build rule for target.
GenSysSchema/fast:
	$(MAKE) -f scripts/CMakeFiles/GenSysSchema.dir/build.make scripts/CMakeFiles/GenSysSchema.dir/build
.PHONY : GenSysSchema/fast

#=============================================================================
# Target rules for targets named comp_sql

# Build rule for target.
comp_sql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comp_sql
.PHONY : comp_sql

# fast build rule for target.
comp_sql/fast:
	$(MAKE) -f scripts/CMakeFiles/comp_sql.dir/build.make scripts/CMakeFiles/comp_sql.dir/build
.PHONY : comp_sql/fast

#=============================================================================
# Target rules for targets named test-mtr

# Build rule for target.
test-mtr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-mtr
.PHONY : test-mtr

# fast build rule for target.
test-mtr/fast:
	$(MAKE) -f mysql-test/CMakeFiles/test-mtr.dir/build.make mysql-test/CMakeFiles/test-mtr.dir/build
.PHONY : test-mtr/fast

#=============================================================================
# Target rules for targets named my_safe_process

# Build rule for target.
my_safe_process: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_safe_process
.PHONY : my_safe_process

# fast build rule for target.
my_safe_process/fast:
	$(MAKE) -f mysql-test/lib/My/SafeProcess/CMakeFiles/my_safe_process.dir/build.make mysql-test/lib/My/SafeProcess/CMakeFiles/my_safe_process.dir/build
.PHONY : my_safe_process/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... INFO_BIN"
	@echo "... INFO_SRC"
	@echo "... abi_check"
	@echo "... abi_check_all"
	@echo "... ctags"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... tags"
	@echo "... test"
	@echo "... zlib"
	@echo "... yassl"
	@echo "... taocrypt"
	@echo "... edit"
	@echo "... event"
	@echo "... event_share"
	@echo "... perfschema"
	@echo "... pfs-t"
	@echo "... pfs_account-oom-t"
	@echo "... pfs_connect_attr-t"
	@echo "... pfs_host-oom-t"
	@echo "... pfs_instr-oom-t"
	@echo "... pfs_instr-t"
	@echo "... pfs_instr_class-oom-t"
	@echo "... pfs_instr_class-t"
	@echo "... pfs_misc-t"
	@echo "... pfs_noop-t"
	@echo "... pfs_server_stubs"
	@echo "... pfs_user-oom-t"
	@echo "... myisam"
	@echo "... myisam_embedded"
	@echo "... myisam_ftdump"
	@echo "... myisamchk"
	@echo "... myisamlog"
	@echo "... myisampack"
	@echo "... partition"
	@echo "... partition_embedded"
	@echo "... federated"
	@echo "... federated_embedded"
	@echo "... myisammrg"
	@echo "... myisammrg_embedded"
	@echo "... example"
	@echo "... archive"
	@echo "... heap"
	@echo "... heap_embedded"
	@echo "... hp_test1"
	@echo "... hp_test2"
	@echo "... innobase"
	@echo "... blackhole"
	@echo "... blackhole_embedded"
	@echo "... csv"
	@echo "... audit_null"
	@echo "... test_security_context"
	@echo "... rewrite_example"
	@echo "... ftexample"
	@echo "... ngram_parser"
	@echo "... validate_password"
	@echo "... replication_observers_example"
	@echo "... auth"
	@echo "... auth_socket"
	@echo "... auth_test_plugin"
	@echo "... mysql_no_login"
	@echo "... qa_auth_client"
	@echo "... qa_auth_interface"
	@echo "... qa_auth_server"
	@echo "... test_session_detach"
	@echo "... test_session_in_thd"
	@echo "... test_session_info"
	@echo "... test_sql_2_sessions"
	@echo "... test_sql_all_col_types"
	@echo "... test_sql_cmds_1"
	@echo "... test_sql_commit"
	@echo "... test_sql_complex"
	@echo "... test_sql_errors"
	@echo "... test_sql_lock"
	@echo "... test_sql_processlist"
	@echo "... test_sql_replication"
	@echo "... test_sql_shutdown"
	@echo "... test_sql_sqlmode"
	@echo "... test_sql_stored_procedures_functions"
	@echo "... test_sql_views_triggers"
	@echo "... test_x_sessions_deinit"
	@echo "... test_x_sessions_init"
	@echo "... daemon_example"
	@echo "... semisync_master"
	@echo "... semisync_slave"
	@echo "... version_token"
	@echo "... test_framework"
	@echo "... test_services"
	@echo "... test_services_thread"
	@echo "... rewriter"
	@echo "... dbug"
	@echo "... conf_to_src"
	@echo "... strings"
	@echo "... vio"
	@echo "... re"
	@echo "... regex"
	@echo "... base64_test"
	@echo "... mysys"
	@echo "... queues"
	@echo "... thr_lock"
	@echo "... mysys_ssl"
	@echo "... clientlib"
	@echo "... libmysql"
	@echo "... libmysql_api_test"
	@echo "... mysqlclient"
	@echo "... binlogevents_static"
	@echo "... binlogstandalone_shared"
	@echo "... binlogstandalone_static"
	@echo "... test-unit"
	@echo "... no_plan-t"
	@echo "... simple-t"
	@echo "... skip-t"
	@echo "... skip_all-t"
	@echo "... todo-t"
	@echo "... mytap"
	@echo "... basic-t"
	@echo "... GenError"
	@echo "... comp_err"
	@echo "... innochecksum"
	@echo "... lz4_lib"
	@echo "... my_print_defaults"
	@echo "... perror"
	@echo "... replace"
	@echo "... resolve_stack_dump"
	@echo "... resolveip"
	@echo "... boost_lib"
	@echo "... mysql"
	@echo "... mysql_config_editor"
	@echo "... mysql_install_db"
	@echo "... mysql_plugin"
	@echo "... mysql_secure_installation"
	@echo "... mysql_ssl_rsa_setup"
	@echo "... mysql_upgrade"
	@echo "... mysqladmin"
	@echo "... mysqlbinlog"
	@echo "... mysqlcheck"
	@echo "... mysqlcheck_core"
	@echo "... mysqldump"
	@echo "... mysqlimport"
	@echo "... mysqlshow"
	@echo "... mysqlslap"
	@echo "... mysqltest"
	@echo "... client_base"
	@echo "... mysqlpump"
	@echo "... mysqlpump_lib"
	@echo "... mysqlservices"
	@echo "... bug25714"
	@echo "... mysql_client_test"
	@echo "... GenDigestServerSource"
	@echo "... GenServerSource"
	@echo "... binlog"
	@echo "... dist"
	@echo "... distclean"
	@echo "... gen_lex_hash"
	@echo "... gen_lex_token"
	@echo "... locking_service"
	@echo "... master"
	@echo "... mysql_tzinfo_to_sql"
	@echo "... mysqld"
	@echo "... rpl"
	@echo "... show-dist-name"
	@echo "... slave"
	@echo "... sql"
	@echo "... sqlgunitlib"
	@echo "... udf_example"
	@echo "... GenYaccEmbeddedSource"
	@echo "... mysqlserver"
	@echo "... sql_embedded"
	@echo "... mysql_client_test_embedded"
	@echo "... mysql_embedded"
	@echo "... mysqltest_embedded"
	@echo "... GenBootstrapPriv"
	@echo "... GenFixPrivs"
	@echo "... GenSysSchema"
	@echo "... comp_sql"
	@echo "... test-mtr"
	@echo "... my_safe_process"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

